---
- name: 
  hosts: all
  become: true
  tasks:
  - name:
    user:
      name: "{{ USER_NAME }}"
  - name:
    user:
      name: "{{ USER_NAME }}"
      password: "{{ PASSWORD | password_hash('sha512') }}"
